title: Learn more about veganism!
author: legasso
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  You don't have to be vegan to want to learn more about veganism.
  Learn about foods you can eat and all the good things that 
  being vegan means. Make a difference in your life and in the life of others.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
